baseURL = 'https://sklpsdmockups.onrender.com/'
languageCode = 'el'
title = 'Home'
paginate = "21"
paginatePath = ""
removePathAccents = false
assetDir = "static"

[outputs]
  home = ["HTML"]
  page = ["HTML"]

[params]
  food = true

[taxonomies]
  label = "labels"
  tag = "gencat"
  category = "categories"
  orofos = "orofos"
  promo = "promo"
 
  publication_type = "publication_types"
  author = "authors"
  layout = ""

[related]
  includeNewer = false
  threshold = 85
  toLower = false

  [[related.indices]]
  name = "categories"
  weight = 50

   [[related.indices]]
  name = "labels"
  weight = 45

   [[related.indices]]
  name = "promo"
  weight = 45

