baseURL = 'https://sklpsdmockups.onrender.com/'
languageCode = 'el'
title = 'PSDMockups'
paginate = "16"
paginatePath = ""
removePathAccents = false
assetDir = "static"

[taxonomies]
  label = "labels"
  tag = "tags"
  category = "categories"
  orofos = "orofos"
  promo = "promo"
  gencat= "gencat"
  publication_type = "publication_types"
  author = "authors"
  layout = ""

